### PR TITLE
Add Dockerfile and basic build/usage guide

### PR DESCRIPTION
**Pull request by Flexusma**
Hey, as promised in #https://github.com/pruvious/pruvious/issues/51#issuecomment-2323297054 here is my proposal for some docker related stuff.
This PR includes:
 - Dockerfile to build a somewhat optimized production container
 - /docker directory with
   - a docker-compose.yml to use a locally built image
   - a docker-compose.traefik.yml file that is an example for a production docker setup (using traefik as a reverse proxy) 
   - a small Guide on how to use the files
   
Feel free to make changes to this where needed (I didn't sanity check some of the comments I wrote :p)

### CODE REVIEW

**Comment by murisceman** [comment]
Hey, thank you so much for this PR! Could you please "Allow edits from maintainers" so I can update some comments?

**Comment by Flexusma** [comment]
> Hey, thank you so much for this PR! Could you please "Allow edits from maintainers" so I can update some comments?

Seems like this is currently not possible because the fork is on our org account (https://github.com/orgs/community/discussions/5634). I'll invite you directly as a workaround. Not ideal but will do...

**Comment by murisceman** [comment]
Huh, I didn't know about this limitation.  

Thanks for the invite! I committed some comment changes. Could you please review them to see if they are correct?

https://github.com/pruvious/pruvious/pull/55/commits/9764ada67c18ae0f165437d48baa09cc5dc0b0ab

**Comment by Flexusma** [comment]
> Huh, I didn't know about this limitation.
Me neither :/

I'll have a look. I could have spent a bit cross-checking some of the stuff I wrote, some of it wasn't great. Sorry for the inconvenience and you having to edit some of that stuff. I'll make sure to check again next time I do sth after a long work day in the evening :p

**Comment by murisceman** [comment]
Not a problem at all! ^^

**Comment by Flexusma** [comment]
Your changes were great! I've added a quick explainer to the --arch flag in the Dockerfile just in case someone tries to deploy on arm and is confused why sharp throws an error.

Also added a reference to the pruvious cli/deploy section on pruvious.com on top of the guide. Dome less technical people might try and use the docker way because "usually it's easier" instead of just using the "better" CLI way :)

**Comment by murisceman** [comment]
Awesome, thank you!

**Comment by abbjetmus** [comment]
Hi @Flexusma!

I've tried with the suggested dockerfile to deploy to my VPS but without success.

First I got:

```FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----```

Then I added 

```
# Set Node.js memory limit for the build process
ENV NODE_OPTIONS="--max-old-space-size=4096"```
Which seems to let me get further but I finally get stuck at this step:

```
------------------------- Fri Jan 03 2025 13:04:23 GMT+0000 (Coordinated Universal Time)
Build started for brf-samlat-landningpage
Ignore warnings for unconsumed build-args if there is any
Step 1/20 : FROM node:current as base

---> b536d17a0f8a
Step 2/20 : LABEL authors="pruvious"

---> Using cache
---> 071a0358ed74
Step 3/20 : RUN mkdir -p /app

---> Using cache
---> 64d87e0c935c
Step 4/20 : WORKDIR /app

---> Using cache
---> a1398c8871f4
Step 5/20 : ADD https://www.google.com /time.now


---> 3e8e575b304e
Step 6/20 : ENV NODE_ENV=production

---> Running in 21abee99d873
---> Removed intermediate container 21abee99d873
---> b1a7d504b569
Step 7/20 : FROM base as build

---> b1a7d504b569
Step 8/20 : RUN apt-get update -y && apt-get install -y openssl git

---> Running in 7f68bfb703c6
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8789 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [8856 B]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [240 kB]
Fetched 9292 kB in 3s (2999 kB/s)
Reading package lists...

Reading package lists...

Building dependency tree...

Reading state information...

openssl is already the newest version (3.0.15-1~deb12u1).
openssl set to manually installed.
git is already the newest version (1:2.39.5-0+deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
---> Removed intermediate container 7f68bfb703c6
---> 112701dbe5f1
Step 9/20 : COPY --link package.json package-lock.json ./

---> 75e22c8ba9cc
Step 10/20 : ENV NODE_OPTIONS="--max-old-space-size=4096"

---> Running in af080532ee22
---> Removed intermediate container af080532ee22
---> 26ec5b3f4a91
Step 11/20 : RUN npm install --production=false --arch=x64

---> Running in 0a45dae6889d
npm warn config production Use `--omit=dev` instead.

npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported

npm warn deprecated npmlog@6.0.2: This package is no longer supported.

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

npm warn deprecated gauge@4.0.4: This package is no longer supported.

npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.

npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

npm warn deprecated npmlog@5.0.1: This package is no longer supported.

npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.

npm warn deprecated gauge@3.0.2: This package is no longer supported.

> postinstall
> nuxt prepare
ℹ Using 2024-04-03 as fallback compatibility date.
✔ Types generated in .nuxt
added 1180 packages, and audited 1182 packages in 1m

196 packages are looking for funding
run `npm fund` for details
2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm notice
npm notice New major version of npm available! 10.9.2 -> 11.0.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.0.0
npm notice To update run: npm install -g npm@11.0.0
npm notice

---> Removed intermediate container 0a45dae6889d
---> ab5074c02dfa
Step 12/20 : COPY --link . .

---> 795e96abbca8
Step 13/20 : RUN npm run build

---> Running in 2383b33f2168
> build
> nuxt build
Nuxt 3.14.0 with Nitro 2.10.4
ℹ .nuxt/dist/client/_nuxt/D1uhJVYI.js                                        1.62 kB │ gzip:   0.92 kB
ℹ .nuxt/dist/client/_nuxt/SwHZ02TJ.js                                        1.71 kB │ gzip:   0.81 kB
ℹ .nuxt/dist/client/_nuxt/vFywUwxW.js                                        1.77 kB │ gzip:   0.99 kB
ℹ .nuxt/dist/client/_nuxt/CWPEs9ww.js                                        1.79 kB │ gzip:   0.97 kB
ℹ .nuxt/dist/client/_nuxt/BrLTJLp-.js                                        1.87 kB │ gzip:   0.98 kB
ℹ .nuxt/dist/client/_nuxt/DrEPBKyN.js                                        1.92 kB │ gzip:   1.02 kB
ℹ .nuxt/dist/client/_nuxt/otDy8Fff.js                                        1.92 kB │ gzip:   1.07 kB
ℹ .nuxt/dist/client/_nuxt/VFJKQKIL.js                                        1.92 kB │ gzip:   0.80 kB
ℹ .nuxt/dist/client/_nuxt/DfURXVuG.js                                        1.93 kB │ gzip:   0.97 kB
ℹ .nuxt/dist/client/_nuxt/pXJCYlTK.js                                        1.99 kB │ gzip:   1.00 kB
ℹ .nuxt/dist/client/_nuxt/B9GroJRb.js                                        2.08 kB │ gzip:   1.11 kB
ℹ .nuxt/dist/client/_nuxt/BKHCpGUI.js                                        2.09 kB │ gzip:   1.03 kB
ℹ .nuxt/dist/client/_nuxt/C2wQawgb.js                                        2.18 kB │ gzip:   1.09 kB
ℹ .nuxt/dist/client/_nuxt/B9Dgb5Wp.js                                        2.19 kB │ gzip:   1.15 kB
ℹ .nuxt/dist/client/_nuxt/GK4d3MvU.js                                        2.29 kB │ gzip:   1.13 kB
ℹ .nuxt/dist/client/_nuxt/BzWABHnx.js                                        2.32 kB │ gzip:   0.96 kB
ℹ .nuxt/dist/client/_nuxt/BqMNW3wU.js                                        2.33 kB │ gzip:   1.19 kB
ℹ .nuxt/dist/client/_nuxt/C2j0qWti.js                                        2.40 kB │ gzip:   1.06 kB
ℹ .nuxt/dist/client/_nuxt/DmIWHUzp.js                                        2.41 kB │ gzip:   1.14 kB
ℹ .nuxt/dist/client/_nuxt/BbtVH-xq.js                                        2.47 kB │ gzip:   1.23 kB
ℹ .nuxt/dist/client/_nuxt/CxByRLEq.js                                        2.55 kB │ gzip:   1.17 kB
ℹ .nuxt/dist/client/_nuxt/Dz5MRZdF.js                                        2.56 kB │ gzip:   1.22 kB
ℹ .nuxt/dist/client/_nuxt/CT3ms_ti.js                                        2.61 kB │ gzip:   1.28 kB
ℹ .nuxt/dist/client/_nuxt/Bd9eJEmg.js                                        2.66 kB │ gzip:   1.77 kB
ℹ .nuxt/dist/client/_nuxt/BJLtGjcM.js                                        2.79 kB │ gzip:   1.44 kB
ℹ .nuxt/dist/client/_nuxt/BT2ay0Q6.js                                        2.85 kB │ gzip:   1.32 kB
ℹ .nuxt/dist/client/_nuxt/BMyOn5uw.js                                        2.92 kB │ gzip:   1.42 kB
ℹ .nuxt/dist/client/_nuxt/BBfYMc0S.js                                        3.01 kB │ gzip:   1.52 kB
ℹ .nuxt/dist/client/_nuxt/DmDImWF2.js                                        3.08 kB │ gzip:   1.42 kB
ℹ .nuxt/dist/client/_nuxt/_qbgsTA3.js                                        3.15 kB │ gzip:   1.45 kB
ℹ .nuxt/dist/client/_nuxt/CqgceZ5w.js                                        3.18 kB │ gzip:   1.56 kB
ℹ .nuxt/dist/client/_nuxt/C2680M5k.js                                        3.31 kB │ gzip:   1.55 kB
ℹ .nuxt/dist/client/_nuxt/X1lJU4_n.js                                        3.32 kB │ gzip:   1.39 kB
ℹ .nuxt/dist/client/_nuxt/DStuNbiO.js                                        3.35 kB │ gzip:   1.37 kB
ℹ .nuxt/dist/client/_nuxt/CxGe2vvf.js                                        3.40 kB │ gzip:   0.97 kB
ℹ .nuxt/dist/client/_nuxt/CQxXtWOV.js                                        3.41 kB │ gzip:   1.54 kB
ℹ .nuxt/dist/client/_nuxt/BQ_kqO5e.js                                        3.48 kB │ gzip:   1.56 kB
ℹ .nuxt/dist/client/_nuxt/ZbNvkrDt.js                                        3.52 kB │ gzip:   1.59 kB
ℹ .nuxt/dist/client/_nuxt/0jtkdLKJ.js                                        3.77 kB │ gzip:   1.80 kB
ℹ .nuxt/dist/client/_nuxt/DReb7RVv.js                                        3.78 kB │ gzip:   1.71 kB
ℹ .nuxt/dist/client/_nuxt/_WfInyJq.js                                        3.87 kB │ gzip:   1.81 kB
ℹ .nuxt/dist/client/_nuxt/EocEDf5Y.js                                        4.02 kB │ gzip:   1.88 kB
ℹ .nuxt/dist/client/_nuxt/Bn0I3Kw3.js                                        4.04 kB │ gzip:   1.59 kB
ℹ .nuxt/dist/client/_nuxt/CQuSVRGY.js                                        4.15 kB │ gzip:   1.63 kB
ℹ .nuxt/dist/client/_nuxt/BjlgwJLp.js                                        4.19 kB │ gzip:   1.91 kB
ℹ .nuxt/dist/client/_nuxt/B4-IeK-K.js                                        4.28 kB │ gzip:   1.86 kB
ℹ .nuxt/dist/client/_nuxt/DuwR9r4X.js                                        4.33 kB │ gzip:   1.82 kB
ℹ .nuxt/dist/client/_nuxt/CVmV1DAC.js                                        4.43 kB │ gzip:   1.99 kB
ℹ .nuxt/dist/client/_nuxt/DCIndmTJ.js                                        4.51 kB │ gzip:   1.82 kB
ℹ .nuxt/dist/client/_nuxt/CxqNhXNv.js                                        4.54 kB │ gzip:   1.97 kB
ℹ .nuxt/dist/client/_nuxt/5Xhp7gq_.js                                        4.60 kB │ gzip:   1.92 kB
ℹ .nuxt/dist/client/_nuxt/BemczXe5.js                                        4.61 kB │ gzip:   1.21 kB
ℹ .nuxt/dist/client/_nuxt/Dy0uiCEk.js                                        4.85 kB │ gzip:   1.33 kB
ℹ .nuxt/dist/client/_nuxt/SMau5pkX.js                                        4.86 kB │ gzip:   2.05 kB
ℹ .nuxt/dist/client/_nuxt/BisJ--TA.js                                        5.13 kB │ gzip:   2.25 kB
ℹ .nuxt/dist/client/_nuxt/D0G5XTSi.js                                        5.15 kB │ gzip:   1.84 kB
ℹ .nuxt/dist/client/_nuxt/Cqvro3eS.js                                        5.22 kB │ gzip:   2.30 kB
ℹ .nuxt/dist/client/_nuxt/DhafH-ei.js                                        5.26 kB │ gzip:   2.13 kB
ℹ .nuxt/dist/client/_nuxt/BCMGFPmB.js                                        5.28 kB │ gzip:   1.93 kB
ℹ .nuxt/dist/client/_nuxt/B5FS1Byw.js                                        5.30 kB │ gzip:   2.38 kB
ℹ .nuxt/dist/client/_nuxt/BFp8oQU-.js                                        5.50 kB │ gzip:   2.17 kB
ℹ .nuxt/dist/client/_nuxt/DQGKTsmB.js                                        5.57 kB │ gzip:   1.79 kB
ℹ .nuxt/dist/client/_nuxt/COcokqe6.js                                        5.62 kB │ gzip:   2.19 kB
ℹ .nuxt/dist/client/_nuxt/_tUUsXGS.js                                        5.68 kB │ gzip:   1.91 kB
ℹ .nuxt/dist/client/_nuxt/BRezrBk8.js                                        5.69 kB │ gzip:   2.44 kB
ℹ .nuxt/dist/client/_nuxt/DycXxftp.js                                        5.96 kB │ gzip:   2.23 kB
ℹ .nuxt/dist/client/_nuxt/DnSET1UW.js                                        5.98 kB │ gzip:   2.55 kB
ℹ .nuxt/dist/client/_nuxt/ukCpd5G3.js                                        6.36 kB │ gzip:   2.73 kB
ℹ .nuxt/dist/client/_nuxt/eZt9C8XI.js                                        6.68 kB │ gzip:   2.72 kB
ℹ .nuxt/dist/client/_nuxt/B74uaQvV.js                                        6.71 kB │ gzip:   2.11 kB
ℹ .nuxt/dist/client/_nuxt/M9KAj5Cj.js                                        7.22 kB │ gzip:   2.49 kB
ℹ .nuxt/dist/client/_nuxt/CcFs_tAC.js                                        7.51 kB │ gzip:   3.12 kB
ℹ .nuxt/dist/client/_nuxt/B7tx7-O-.js                                        7.56 kB │ gzip:   2.91 kB
ℹ .nuxt/dist/client/_nuxt/BsQEiI8B.js                                        7.64 kB │ gzip:   3.11 kB
ℹ .nuxt/dist/client/_nuxt/Bn78-9CQ.js                                        8.04 kB │ gzip:   2.72 kB
ℹ .nuxt/dist/client/_nuxt/DaFO0SzU.js                                        8.19 kB │ gzip:   3.43 kB
ℹ .nuxt/dist/client/_nuxt/2kls381t.js                                        8.20 kB │ gzip:   3.26 kB
ℹ .nuxt/dist/client/_nuxt/CVQ3yG4M.js                                        8.22 kB │ gzip:   3.31 kB
ℹ .nuxt/dist/client/_nuxt/BwR7YWdi.js                                        8.67 kB │ gzip:   2.97 kB
ℹ .nuxt/dist/client/_nuxt/iU8i5qcX.js                                        8.74 kB │ gzip:   3.44 kB
ℹ .nuxt/dist/client/_nuxt/BzSJozG7.js                                        8.85 kB │ gzip:   3.68 kB
ℹ .nuxt/dist/client/_nuxt/DZzGuN0A.js                                       10.00 kB │ gzip:   3.88 kB
ℹ .nuxt/dist/client/_nuxt/8pH-CELp.js                                       10.07 kB │ gzip:   3.30 kB
ℹ .nuxt/dist/client/_nuxt/Cqd0f5jV.js                                       10.56 kB │ gzip:   4.23 kB
ℹ .nuxt/dist/client/_nuxt/COSgE5fC.js                                       11.10 kB │ gzip:   4.34 kB
ℹ .nuxt/dist/client/_nuxt/BwW2XYHX.js                                       13.78 kB │ gzip:   5.47 kB
ℹ .nuxt/dist/client/_nuxt/DYUuGSxV.js                                       19.14 kB │ gzip:   5.83 kB
ℹ .nuxt/dist/client/_nuxt/C5oqzDSG.js                                       19.83 kB │ gzip:   7.24 kB
ℹ .nuxt/dist/client/_nuxt/CHJPhspH.js                                       23.84 kB │ gzip:   8.00 kB
ℹ .nuxt/dist/client/_nuxt/Bx2zveJz.js                                       34.79 kB │ gzip:  11.37 kB
ℹ .nuxt/dist/client/_nuxt/P34OfQto.js                                       37.62 kB │ gzip:  13.15 kB
ℹ .nuxt/dist/client/_nuxt/CLQ_oLGC.js                                       50.75 kB │ gzip:  14.84 kB
ℹ .nuxt/dist/client/_nuxt/pi42DyEW.js                                       51.46 kB │ gzip:  15.20 kB
ℹ .nuxt/dist/client/_nuxt/I81PCDki.js                                       60.87 kB │ gzip:  22.37 kB
ℹ .nuxt/dist/client/_nuxt/C5Bchp-6.js                                      218.55 kB │ gzip:  82.39 kB
ℹ .nuxt/dist/client/_nuxt/vlaO0oqx.js                                      344.95 kB │ gzip: 105.89 kB
ℹ ✓ built in 26.25s
✔ Client built in 26281ms
ℹ Building server...
ℹ vite v5.4.11 building SSR bundle for production...
ℹ transforming...
ℹ ✓ 600 modules transformed.
ℹ rendering chunks...
EBADENGINE
   package: '@nuxt/kit@3.15.0',

npm
 
WARN
 
EBADENGINE
   required: { node: '>=18.20.5' },

npm
 
WARN
 
EBADENGINE
   current: { node: 'v18.19.0', npm: '10.2.3' }

npm
 
WARN
 
EBADENGINE
 }

npm
 
WARN
 
EBADENGINE
 Unsupported engine {

npm
 
WARN
 
EBADENGINE
   package: 'pruvious@3.14.0',

npm
 
WARN
 
EBADENGINE
   required: { node: '>=20' },

npm
 
WARN
 
EBADENGINE
   current: { node: 'v18.19.0', npm: '10.2.3' }

npm
 
WARN
 
EBADENGINE
 }

WARN
 
deprecated
 @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

npm
 
WARN
 
deprecated
 glob@7.2.3: Glob versions prior to v9 are no longer supported

npm
 
WARN
 
deprecated
 gauge@4.0.4: This package is no longer supported.

npm
 
WARN
 
deprecated
 gauge@3.0.2: This package is no longer supported.

> postinstall
> nuxt prepare
ℹ Using 2024-04-03 as fallback compatibility date.
✔ Types generated in .nuxt
added 1177 packages, and audited 1179 packages in 1m

196 packages are looking for funding
run `npm fund` for details
2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm
 
notice
 

npm
 
notice
 New major version of npm available! 10.2.3 -> 11.0.0

npm
 
notice
 Changelog: <https://github.com/npm/cli/releases/tag/v11.0.0>

npm
 
notice
 Run `npm install -g npm@11.0.0` to update!

npm
 
notice
 

---> Removed intermediate container 6a4d439046f1
---> 9c006123bcbe
Step 8/17 : COPY . .

---> f2f0c6816956
Step 9/17 : RUN npm run build

---> Running in b78659f05525
> build
> nuxt build
Nuxt 3.14.0 with Nitro 2.10.4
[nuxt:tailwindcss] ℹ Using Tailwind CSS from ~/assets/css/tailwind.css
[nuxt:google-fonts] ◐ Downloading fonts...
[nuxt:google-fonts] ✔ https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap
[nuxt:google-fonts] ℹ Inter-400
[nuxt:google-fonts] ✔ Download fonts completed.
[nuxt:google-fonts]
[pruvious] ✔ Database synced in 704 ms
[pruvious] ✔ Pruvious built in 7233 ms
ℹ Building client...
ℹ vite v5.4.11 building for production...
ℹ transforming...
ℹ ✓ 856 modules transformed.
ℹ rendering chunks...
ℹ .nuxt/dist/client/_nuxt/DCIndmTJ.js                                        4.51 kB │ gzip:   1.82 kB
ℹ .nuxt/dist/client/_nuxt/CxqNhXNv.js                                        4.54 kB │ gzip:   1.97 kB
ℹ .nuxt/dist/client/_nuxt/5Xhp7gq_.js                                        4.60 kB │ gzip:   1.92 kB
ℹ .nuxt/dist/client/_nuxt/BemczXe5.js                                        4.61 kB │ gzip:   1.21 kB
ℹ .nuxt/dist/client/_nuxt/Dy0uiCEk.js                                        4.85 kB │ gzip:   1.33 kB
ℹ .nuxt/dist/client/_nuxt/SMau5pkX.js                                        4.86 kB │ gzip:   2.05 kB
ℹ .nuxt/dist/client/_nuxt/BisJ--TA.js                                        5.13 kB │ gzip:   2.25 kB
ℹ .nuxt/dist/client/_nuxt/D0G5XTSi.js                                        5.15 kB │ gzip:   1.84 kB
ℹ .nuxt/dist/client/_nuxt/Cqvro3eS.js                                        5.22 kB │ gzip:   2.30 kB
ℹ .nuxt/dist/client/_nuxt/DhafH-ei.js                                        5.26 kB │ gzip:   2.13 kB
ℹ .nuxt/dist/client/_nuxt/BCMGFPmB.js                                        5.28 kB │ gzip:   1.93 kB
ℹ .nuxt/dist/client/_nuxt/B5FS1Byw.js                                        5.30 kB │ gzip:   2.38 kB
ℹ .nuxt/dist/client/_nuxt/BFp8oQU-.js                                        5.50 kB │ gzip:   2.17 kB
ℹ .nuxt/dist/client/_nuxt/DQGKTsmB.js                                        5.57 kB │ gzip:   1.79 kB
ℹ .nuxt/dist/client/_nuxt/COcokqe6.js                                        5.62 kB │ gzip:   2.19 kB
ℹ .nuxt/dist/client/_nuxt/_tUUsXGS.js                                        5.68 kB │ gzip:   1.91 kB
ℹ .nuxt/dist/client/_nuxt/BRezrBk8.js                                        5.69 kB │ gzip:   2.44 kB
ℹ .nuxt/dist/client/_nuxt/DycXxftp.js                                        5.96 kB │ gzip:   2.23 kB
ℹ .nuxt/dist/client/_nuxt/DnSET1UW.js                                        5.98 kB │ gzip:   2.55 kB
ℹ .nuxt/dist/client/_nuxt/ukCpd5G3.js                                        6.36 kB │ gzip:   2.73 kB
ℹ .nuxt/dist/client/_nuxt/eZt9C8XI.js                                        6.68 kB │ gzip:   2.72 kB
ℹ .nuxt/dist/client/_nuxt/B74uaQvV.js                                        6.71 kB │ gzip:   2.11 kB
ℹ .nuxt/dist/client/_nuxt/M9KAj5Cj.js                                        7.22 kB │ gzip:   2.49 kB
ℹ .nuxt/dist/client/_nuxt/CcFs_tAC.js                                        7.51 kB │ gzip:   3.12 kB
ℹ .nuxt/dist/client/_nuxt/B7tx7-O-.js                                        7.56 kB │ gzip:   2.91 kB
ℹ .nuxt/dist/client/_nuxt/BsQEiI8B.js                                        7.64 kB │ gzip:   3.11 kB
ℹ .nuxt/dist/client/_nuxt/Bn78-9CQ.js                                        8.04 kB │ gzip:   2.72 kB
ℹ .nuxt/dist/client/_nuxt/DaFO0SzU.js                                        8.19 kB │ gzip:   3.43 kB
ℹ .nuxt/dist/client/_nuxt/2kls381t.js                                        8.20 kB │ gzip:   3.26 kB
ℹ .nuxt/dist/client/_nuxt/CVQ3yG4M.js                                        8.22 kB │ gzip:   3.31 kB
ℹ .nuxt/dist/client/_nuxt/BwR7YWdi.js                                        8.67 kB │ gzip:   2.97 kB
ℹ .nuxt/dist/client/_nuxt/iU8i5qcX.js                                        8.74 kB │ gzip:   3.44 kB
ℹ .nuxt/dist/client/_nuxt/BzSJozG7.js                                        8.85 kB │ gzip:   3.68 kB
ℹ .nuxt/dist/client/_nuxt/DZzGuN0A.js                                       10.00 kB │ gzip:   3.88 kB
ℹ .nuxt/dist/client/_nuxt/8pH-CELp.js                                       10.07 kB │ gzip:   3.30 kB
ℹ .nuxt/dist/client/_nuxt/Cqd0f5jV.js                                       10.56 kB │ gzip:   4.23 kB
ℹ .nuxt/dist/client/_nuxt/COSgE5fC.js                                       11.10 kB │ gzip:   4.34 kB
ℹ .nuxt/dist/client/_nuxt/BwW2XYHX.js                                       13.78 kB │ gzip:   5.47 kB
ℹ .nuxt/dist/client/_nuxt/DYUuGSxV.js                                       19.14 kB │ gzip:   5.83 kB
ℹ .nuxt/dist/client/_nuxt/C5oqzDSG.js                                       19.83 kB │ gzip:   7.24 kB
ℹ .nuxt/dist/client/_nuxt/CHJPhspH.js                                       23.84 kB │ gzip:   8.00 kB
ℹ .nuxt/dist/client/_nuxt/Bx2zveJz.js                                       34.79 kB │ gzip:  11.37 kB
ℹ .nuxt/dist/client/_nuxt/P34OfQto.js                                       37.62 kB │ gzip:  13.15 kB
ℹ .nuxt/dist/client/_nuxt/CLQ_oLGC.js                                       50.75 kB │ gzip:  14.84 kB
ℹ .nuxt/dist/client/_nuxt/pi42DyEW.js                                       51.46 kB │ gzip:  15.20 kB
ℹ .nuxt/dist/client/_nuxt/I81PCDki.js                                       60.87 kB │ gzip:  22.37 kB
ℹ .nuxt/dist/client/_nuxt/C5Bchp-6.js                                      218.55 kB │ gzip:  82.39 kB
ℹ .nuxt/dist/client/_nuxt/vlaO0oqx.js                                      344.95 kB │ gzip: 105.89 kB
ℹ ✓ built in 31.28s
✔ Client built in 31324ms
ℹ Building server...
ℹ vite v5.4.11 building SSR bundle for production...
ℹ transforming...
ℹ ✓ 600 modules transformed.
ℹ rendering chunks...
```

This is my dockerfile:

# Use the latest Node.js image as the base
FROM node:current as base
LABEL authors="pruvious"

# Create and set the working directory
RUN mkdir -p /app
WORKDIR /app

# Set the environment to production
ENV NODE_ENV=production

# Build stage
FROM base as build

# Install necessary tools for the build process
RUN apt-get update -y && apt-get install -y openssl git

# Copy package.json and package-lock.json (if available)
COPY --link package.json package-lock.json ./

# Set Node.js memory limit to 4GB for the build process
ENV NODE_OPTIONS="--max-old-space-size=4096"

# Install all dependencies, including devDependencies
# --production=false ensures devDependencies are installed
# --arch=x64 specifies the architecture - this has been added to ensure the build output runs as expected if built on non x64 processors but has to run on an x64 server
# If you plan on running pruvious on an arm or non x64 based host, make sure to remove this argument!
RUN npm install --production=false --arch=x64

# Copy the rest of the application code
COPY --link . .

# Build the Nuxt.js application
RUN npm run build

# Production stage
FROM base
WORKDIR /app

# Set the PORT environment variable
ENV PORT=3000
ENV NODE_ENV=production

# Copy the built application from the build stage
COPY --from=build /app/.output /app/.output

# Optional: Uncomment if you need unbundled dependencies
# COPY --from=build /src/node_modules /src/node_modules

# Expose the port used by the Nuxt.js application
EXPOSE 3000

# Command to run the application
CMD [ "node", ".output/server/index.mjs" ]


Do you have any suggestions what might be the issue?

**Pull request merged**
